<?php
/**
 * Physical Shop template for separate item
 *
 * @author Magento
 */

/**
 * @var $this Edge_Physicalshop_Block_Item
 * @see Edge_Physicalshop_Block_Item
 */
?>
<?php $_physicalshopItem = $this->helper('edge_physicalshop')->getPhysicalshopItemInstance(); ?>

<div class="page-title">
    <h1><?php echo $this->escapeHtml($_physicalshopItem->getLocale()) ?></h1>

    <div class="physicalshop_item_subtitle">
        <p>
            <?php echo $this->escapeHtml($_physicalshopItem->getCountry()) ?> |
            <?php echo $this->escapeHtml($_physicalshopItem->getLocale()) ?>
        </p>
        <br />
    </div>
</div>

<div class="physicalshop_item_view">
    <div class="physicalshop_item_content">
        <p><?php echo $_physicalshopItem->getAddress() ?></p>
        <p><?php echo $_physicalshopItem->getPostalCode() ?></p>
        <br />
        <p>
            <b>Telephone    </b>
            <?php echo $_physicalshopItem->getTelephone() ?>
        </p>
        <p>
            <b>Free Parking </b>
            <?php if ($_physicalshopItem->getFreeParking() == 1): ?>
                <?php echo 'Yes'; ?>
            <?php else: ?>
                <?php echo 'No'; ?>
            <?php endif; ?>
        </p>
        <p>
            <b>GPS          </b>
            <?php echo $_physicalshopItem->getGps() ?>
        </p>
    </div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('edge_physicalshop')->__('Return to list') ?>
        </a>
    </div>
</div>